version: '2'

services:
  app:
    build: ./app
    depends_on:
      - postgres
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './app:/app'
    restart: 'always'
  postgres:
    image: postgres:9.6-alpine
    hostname: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'pg_data:/var/lib/postgresql/data'
volumes:
  pg_data: {}
